version: '3.9'

services:
  monolito_app:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - monolito_db

    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1g
    container_name: monolito_app


  monolito_db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=asistencia
    ports:
      - 3306:3306
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4g
    volumes:
      - db_data_asistencia:/var/lib/mysql
    container_name: monolito_db

volumes:
  db_data_asistencia:
